module.exports = [
    {
        name:'Mario',
        fighter:'01',
        series: 'Super Mario Bros',
        image:'https://www.smashbros.com/assets_v2/img/fighter/mario/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Donkey Kong ',
        fighter:'02',
        series: 'Donkey Kong',
        image:'https://www.smashbros.com/assets_v2/img/fighter/donkey_kong/main.png',       
        trailer:'https://www.youtube.com/embed/_5p0SiWHwvw', 
        background:'https://images2.alphacoders.com/475/thumb-1920-475417.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Donkey_Kong_logo.png/640px-Donkey_Kong_logo.png',
    },
    {
        name:'Link',
        fighter:'03',
        series: 'Legend of Zelda',
        image:'https://www.smashbros.com/assets_v2/img/fighter/link/main.png',       
        trailer:'https://www.youtube.com/embed/Pi-MRZBP91I', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Saga_The_Legend_of_Zelda.png/640px-Saga_The_Legend_of_Zelda.png',
    },
    {
        name:'Samus',
        fighter:'04',
        series: 'Metroid',
        image:'https://www.smashbros.com/assets_v2/img/fighter/samus/main.png',       
        trailer:'https://www.youtube.com/embed/V_XnbTayTH4', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2021/06/metroid_dread_3.jpg?fit=2048%2C1319&ssl=1',
        logo:'https://upload.wikimedia.org/wikipedia/commons/6/64/Metroid-Logo.png',
    },
    {
        name:'Dark Samus',
        fighter:'4E',
        series: 'Metroid',
        image:'https://www.smashbros.com/assets_v2/img/fighter/dark_samus/main.png',       
        trailer:'https://www.youtube.com/embed/V_XnbTayTH4', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2021/06/metroid_dread_3.jpg?fit=2048%2C1319&ssl=1',
        logo:'https://upload.wikimedia.org/wikipedia/commons/6/64/Metroid-Logo.png',
    },
    {
        name:'Yoshi',
        fighter:'05',
        series: 'Yoshi Island',
        image:'https://www.smashbros.com/assets_v2/img/fighter/yoshi/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Kirby',
        fighter:'06',
        series: 'Kirby Dreamland',
        image:'https://www.smashbros.com/assets_v2/img/fighter/kirby/main.png',       
        trailer:'https://www.youtube.com/embed/H3LAkr0ANgw', 
        background:'https://images2.alphacoders.com/987/987537.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kirby-Logo-New.svg/640px-Kirby-Logo-New.svg.png',
    },
    {
        name:'Fox',
        fighter:'07',
        series: 'Starfox',
        image:'https://www.smashbros.com/assets_v2/img/fighter/fox/main.png',       
        trailer:'https://www.youtube.com/embed/kexWqX34E7w', 
        background:'https://cdn.fansshare.com/image/starfoxadventures/starfox-assault-ships-nintendo-games-hd-wallpaper-star-fox-assault-639424619.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/StarFox_Sembol%C3%BC.webp/640px-StarFox_Sembol%C3%BC.webp.png',
    },
    {
        name:'Pikachu',
        fighter:'08',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/pikachu/main.png',       
        trailer:'https://www.youtube.com/embed/1OsAunHsY48', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'Luigi',
        fighter:'09',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/luigi/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Ness',
        fighter:'10',
        series: 'Earthbound',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ness/main.png',       
        trailer:'https://www.youtube.com/embed/KXQqhRETBeE', 
        background:'https://images6.alphacoders.com/986/thumb-1920-986517.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/da/EarthBound_Logo.png/640px-EarthBound_Logo.png',
    },
    {
        name:'Captain Falcon',
        fighter:'11',
        series: 'Starfox',
        image:'https://www.smashbros.com/assets_v2/img/fighter/captain_falcon/main.png',       
        trailer:'https://www.youtube.com/embed/b_n0uJOiKG8', 
        background:'https://cdn.fansshare.com/image/starfoxadventures/starfox-assault-ships-nintendo-games-hd-wallpaper-star-fox-assault-639424619.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/StarFox_Sembol%C3%BC.webp/640px-StarFox_Sembol%C3%BC.webp.png',
    },
    {
        name:'Jigglypuff',
        fighter:'12',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/jigglypuff/main.png',       
        trailer:'https://www.youtube.com/embed/tfQj1aQz8d8', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'Peach',
        fighter:'13',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/peach/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Daisy',
        fighter:'13E ',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/daisy/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },{
        name:'Bowser',
        fighter:'14',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/bowser/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Ice Climbers',
        fighter:'15',
        series: 'Ice Climbers',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ice_climbers/main.png',       
        trailer:'https://www.youtube.com/embed/FUzcsIjn4LY', 
        background:'https://assets.nintendo.com/image/upload/c_fill,w_1200/q_auto:best/f_auto/dpr_2.0/ncom/en_US/games/switch/a/arcade-archives-ice-climber-switch/hero',
        logo:'https://ssb.wiki.gallery/images/1/1d/IceClimberSymbol.svg',
    },
    {
        name:'Shiek',
        fighter:'16',
        series: 'Legend of Zelda',
        image:'https://www.smashbros.com/assets_v2/img/fighter/sheik/main.png',       
        trailer:'https://www.youtube.com/embed/b2nKt-uf24Y', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Saga_The_Legend_of_Zelda.png/640px-Saga_The_Legend_of_Zelda.png',
    },
    {
        name:'Zelda',
        fighter:'17',
        series: 'Legend of Zelda',
        image:'https://www.smashbros.com/assets_v2/img/fighter/zelda/main.png',       
        trailer:'https://www.youtube.com/embed/b2nKt-uf24Y', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Saga_The_Legend_of_Zelda.png/640px-Saga_The_Legend_of_Zelda.png',
    },
    {
        name:'Dr. Mario',
        fighter:'18',
        series: 'Dr. Mario 64',
        image:'https://www.smashbros.com/assets_v2/img/fighter/dr_mario/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Pichu',
        fighter:'19',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/pichu/main.png',       
        trailer:'https://www.youtube.com/embed/tfQj1aQz8d8', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'Falco',
        fighter:'20',
        series: 'Super Smash Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/falco/main.png',       
        trailer:'https://www.youtube.com/embed/b_n0uJOiKG8', 
        background:'https://cdn.fansshare.com/image/starfoxadventures/starfox-assault-ships-nintendo-games-hd-wallpaper-star-fox-assault-639424619.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/StarFox_Sembol%C3%BC.webp/640px-StarFox_Sembol%C3%BC.webp.png',
    },
    {
        name:'Marth',
        fighter:'21',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/marth/main.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Lucina',
        fighter:'21E',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/lucina/main.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Young Link',
        fighter:'22',
        series: 'Legend of Zelda',
        image:'https://www.smashbros.com/assets_v2/img/fighter/young_link/main.png',       
        trailer:'https://www.youtube.com/embed/b2nKt-uf24Y', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Saga_The_Legend_of_Zelda.png/640px-Saga_The_Legend_of_Zelda.png',
    },
    {
        name:'Ganondorf',
        fighter:'23',
        series: 'Legend of Zelda ',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ganondorf/main.png',       
        trailer:'https://www.youtube.com/embed/b2nKt-uf24Y', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1f/Saga_The_Legend_of_Zelda.png/640px-Saga_The_Legend_of_Zelda.png',
    },
    {
        name:'Mewtwo',
        fighter:'24',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/mewtwo/main.png',       
        trailer:'https://www.youtube.com/embed/GmQI4ZBAmp4', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'Roy',
        fighter:'25',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/roy/main.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Chrom',
        fighter:'25E',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/chrom/main.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Mr. Game and Watch',
        fighter:'26',
        series: 'Game and Watch',
        image:'https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/main.png',       
        trailer:'https://www.youtube.com/embed/Ic0xR07DhSY', 
        background:'https://www.smashbros.com/assets_v2/img/fighter/mr_game_and_watch/ss_2.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Super_Smash_Bros._Ultimate_logo.svg/640px-Super_Smash_Bros._Ultimate_logo.svg.png',
    },
    {
        name:'Meta Knight ',
        fighter:'27',
        series: 'Kirby Dreamland',
        image:'https://www.smashbros.com/assets_v2/img/fighter/meta_knight/main.png',       
        trailer:'https://www.youtube.com/embed/zAQZY2UVcoQ', 
        background:'https://images2.alphacoders.com/987/987537.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kirby-Logo-New.svg/640px-Kirby-Logo-New.svg.png',
    },
    {
        name:'Pit',
        fighter:'28',
        series: 'Kid Icarus',
        image:'https://www.smashbros.com/assets_v2/img/fighter/pit/main.png',       
        trailer:'https://www.youtube.com/embed/WGR8wXl4QTM', 
        background:'https://wallpapercave.com/wp/1ZAMTq2.jpg',
        logo:'https://ssb.wiki.gallery/images/5/52/KidIcarusSymbol.svg',
    },
    {
        name:'Dark Pit',
        fighter:'28E',
        series: 'Kid Icarus',
        image:'https://www.smashbros.com/assets_v2/img/fighter/dark_pit/main.png',       
        trailer:'https://www.youtube.com/embed/WGR8wXl4QTM', 
        background:'https://wallpapercave.com/wp/1ZAMTq2.jpg',
        logo:'https://ssb.wiki.gallery/images/5/52/KidIcarusSymbol.svg',
    },
    {
        name:'Zero Suit Samus',
        fighter:'29',
        series: 'Metroid',
        image:'https://www.smashbros.com/assets_v2/img/fighter/zero_suit_samus/main.png',       
        trailer:'https://www.youtube.com/embed/AOvefm5U250', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2021/06/metroid_dread_3.jpg?fit=2048%2C1319&ssl=1',
        logo:'https://upload.wikimedia.org/wikipedia/commons/6/64/Metroid-Logo.png',
    },
    {
        name:'Wario',
        fighter:'30',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/wario/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Solid Snake',
        fighter:'31',
        series: 'Metal Gear Solid ',
        image:'https://www.smashbros.com/assets_v2/img/fighter/snake/main.png',       
        trailer:'https://www.youtube.com/embed/C19ap2M7DDE', 
        background:'https://wallpaperaccess.com/full/3470516.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b5/Metal_Gear_Solid_logo.png/640px-Metal_Gear_Solid_logo.png',
    },
    {
        name:'Ike ',
        fighter:'32',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ike/main.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Pokemon Trainer',
        fighter:'33-35',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/pokemon_trainer/main.png',       
        trailer:'https://www.youtube.com/embed/GmQI4ZBAmp4', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'Diddy Kong',
        fighter:'36',
        series: 'Donkey Kong',
        image:'https://www.smashbros.com/assets_v2/img/fighter/diddy_kong/main.png',       
        trailer:'https://www.youtube.com/embed/_5p0SiWHwvw', 
        background:'https://images2.alphacoders.com/475/thumb-1920-475417.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Donkey_Kong_logo.png/640px-Donkey_Kong_logo.png',
    },
    {
        name:'Lucas',
        fighter:'37',
        series: 'Earthbound',
        image:'https://www.smashbros.com/assets_v2/img/fighter/lucas/main.png',       
        trailer:'https://www.youtube.com/embed/KXQqhRETBeE', 
        background:'https://images6.alphacoders.com/986/thumb-1920-986517.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/d/da/EarthBound_Logo.png',
    },
    {
        name:'Sonic',
        fighter:'38',
        series: 'Sonic the Hedgehog',
        image:'https://www.smashbros.com/assets_v2/img/fighter/sonic/main.png',       
        trailer:'https://www.youtube.com/embed/CuTcBAkyNL4', 
        background:'https://images2.alphacoders.com/237/237222.png',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Sonic_the_Hedgehog_1991_logo.webp/640px-Sonic_the_Hedgehog_1991_logo.webp.png',
    },
    {
        name:'King Dedede',
        fighter:'39',
        series: 'Kirby Dreamland',
        image:'https://www.smashbros.com/assets_v2/img/fighter/king_dedede/main.png',       
        trailer:'https://www.youtube.com/embed/zAQZY2UVcoQ', 
        background:'https://gameranx.com/wp-content/uploads/2017/11/Kirby-Battle-1920P-Wallaper.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Kirby-Logo-New.svg/640px-Kirby-Logo-New.svg.png',
    },
    {
        name:'Olimar',
        fighter:'40',
        series: 'Pikmin',
        image:'https://www.smashbros.com/assets_v2/img/fighter/olimar/main.png',       
        trailer:'https://www.youtube.com/embed/EzbAzU02Ngg', 
        background:'https://wallpapercave.com/wp/wp2212905.jpg',
        logo:'https://ssb.wiki.gallery/images/6/61/PikminSymbol.svg',
    },
    {
        name:'Lucario',
        fighter:'41',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/lucario/main.png',       
        trailer:'https://www.youtube.com/embed/GmQI4ZBAmp4', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/640px-International_Pok%C3%A9mon_logo.svg.png',
    },
    {
        name:'R.O.B.',
        fighter:'42',
        series: 'Super Smash Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/rob/main.png',       
        trailer:'https://www.youtube.com/embed/WShCN-AYHqA', 
        background:'https://i.ytimg.com/vi/rTCtOMPwQos/maxresdefault.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/96/Super_Smash_Bros._Ultimate_logo.svg/640px-Super_Smash_Bros._Ultimate_logo.svg.png',
    },
    {
        name:'Toon Link',
        fighter:'43',
        series: 'Legend of Zelda',
        image:'https://www.smashbros.com/assets_v2/img/fighter/toon_link/main.png',       
        trailer:'https://www.youtube.com/embed/Pi-MRZBP91I', 
        background:'https://cdn.vox-cdn.com/uploads/chorus_asset/file/22740692/zelda_skyward_sword_walkthrough_guide_header.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2a/Zelda_Logo.svg/591px-Zelda_Logo.svg.png?20210519005608',
    },
    {
        name:'Wolf',
        fighter:'44',
        series: 'Starfox',
        image:'https://www.smashbros.com/assets_v2/img/fighter/wolf/main.png',       
        trailer:'https://www.youtube.com/embed/b_n0uJOiKG8', 
        background:'https://cdn.fansshare.com/image/starfoxadventures/starfox-assault-ships-nintendo-games-hd-wallpaper-star-fox-assault-639424619.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/2/2d/StarFox_Sembol%C3%BC.webp/640px-StarFox_Sembol%C3%BC.webp.png',
    },
    {
        name:'Villager',
        fighter:'45',
        series: 'Animal Crossing',
        image:'https://www.smashbros.com/assets_v2/img/fighter/villager/main.png',       
        trailer:'https://www.youtube.com/embed/_3YNL0OWio0', 
        background:'https://www.xtrafondos.com/en/descargar.php?id=6456&resolucion=2560x1440',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/5/58/Animal_Crossing_Leaf.png/640px-Animal_Crossing_Leaf.png',
    },
    {
        name:'Mega Man',
        fighter:'46',
        series: 'Mega Man',
        image:'https://www.smashbros.com/assets_v2/img/fighter/mega_man/main.png',       
        trailer:'https://www.youtube.com/embed/aX2KNyaoNV4', 
        background:'https://i.ytimg.com/vi/NF132cqW25w/maxresdefault.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Mega_man_logo.png/640px-Mega_man_logo.png',
    },
    {
        name:'Wii Fit Trainer',
        fighter:'47',
        series: 'Wii Fitt',
        image:'https://www.smashbros.com/assets_v2/img/fighter/wii_fit_trainer/main.png',       
        trailer:'"https://www.youtube.com/embed/BM3K-zjh18Y', 
        background:'https://www.wired.com/images_blogs/photos/uncategorized/2008/03/31/wiifit_2.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/37/Wii_Fit_U_logo.svg/640px-Wii_Fit_U_logo.svg.png',
    },
    {
        name:'Rosalina and Luna',
        fighter:'48',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/rosalina_and_luma/main.png',       
        trailer:'https://www.youtube.com/embed/5kcdRBHM7kM', 
        background:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Little Mac',
        fighter:'49',
        series: 'Punch Out',
        image:'https://www.smashbros.com/assets_v2/img/fighter/little_mac/main.png',       
        trailer:'https://www.youtube.com/embed/gmtrmAvL5aw', 
        background:'https://cdn.fanbyte.com/wp-content/uploads/2018/12/Little-Mac.jpg?x48911',
        logo:'https://upload.wikimedia.org/wikipedia/en/b/be/Punch-Out%21%21_series_logo.png',
    },
    {
        name:'Greninja',
        fighter:'50',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/greninja/main.png',       
        trailer:'https://www.youtube.com/embed/GmQI4ZBAmp4', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/98/International_Pok%C3%A9mon_logo.svg/269px-International_Pok%C3%A9mon_logo.svg.png?20150121202211',
    },
    {
        name:'Mii Brawler',
        fighter:'51',
        series: 'Super Smash Bros.',
        image:'',       
        trailer:'', 
        background:'',
        logo:'',
    },
    {
        name:'Mii SwordFighter',
        fighter:'52',
        series: 'Super Smash Bros.',
        image:'',       
        trailer:'', 
        background:'',
        logo:'',
    },
    {
        name:'Mii Gunner',
        fighter:'53',
        series: 'Super Smash Bros.',
        image:'',       
        trailer:'', 
        background:'',
        logo:'',
    },
    {
        name:'Palutena',
        fighter:'54',
        series: 'Kid Icarus',
        image:'https://www.smashbros.com/assets_v2/img/fighter/palutena/main.png',       
        trailer:'https://www.youtube.com/embed/LVTElnEiDyQ', 
        background:'https://wallpapercave.com/wp/1ZAMTq2.jpg',
        logo:'https://ssb.wiki.gallery/images/5/52/KidIcarusSymbol.svg',
    },
    {
        name:'Pac-Man',
        fighter:'55',
        series: 'Pac-Man',
        image:'https://www.smashbros.com/assets_v2/img/fighter/pac_man/main.png',       
        trailer:'https://www.youtube.com/embed/j_SgOs8vkFE', 
        background:'https://wallpaperaccess.com/full/1390914.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/a/a8/Original_PacMan.png',
    },
    {
        name:'Robin',
        fighter:'56',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/robin/main2.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Shulk',
        fighter:'57',
        series: 'Xenoblade',
        image:'https://www.smashbros.com/assets_v2/img/fighter/shulk/main.png',       
        trailer:'https://www.youtube.com/embed/t-iNpDKuYb8', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2020/05/xenoblade_may_2020_wallpaper1.jpg?ssl=1',
        logo:'https://static.wikia.nocookie.net/logopedia/images/6/65/Xenoblade_JP.png/revision/latest/scale-to-width-down/300?cb=20150217205230',
    },
    {
        name:'Bowser Jr.',
        fighter:'58',
        series: 'Super Mario Bros.',
        image:'https://www.smashbros.com/assets_v2/img/fighter/bowser_jr/main.png',       
        trailer:'https://www.youtube.com/embed/q3AJOSQUWN8', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'',
    },
    {
        name:'Duck Hunt',
        fighter:'59',
        series: 'Duck Hunt Dog',
        image:'https://www.smashbros.com/assets_v2/img/fighter/duck_hunt/main.png',       
        trailer:'https://www.youtube.com/embed/6t5DetuBMOY', 
        background:'https://miro.medium.com/max/1000/1*CHpGqF5_AjZCgQokepOIHQ.jpeg',
        logo:'https://static.wikia.nocookie.net/ssb/images/b/b1/Duck_Hunt_Logo.png/revision/latest?cb=20140911121559',
    },
    {
        name:'Ryu',
        fighter:'60',
        series: 'Street Fighter',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ryu/main.png',       
        trailer:'https://www.youtube.com/embed/1INU3FOJsTw', 
        background:'https://i.ytimg.com/vi/0gfU2A9oX5Y/maxresdefault.jpg',
        logo:'https://assets.stickpng.com/images/580b57fcd9996e24bc43c341.png',
    },
    {
        name:'Ken',
        fighter:'60E',
        series: 'Street Fighter',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ken/main.png',       
        trailer:'', 
        background:'',
        logo:'https://assets.stickpng.com/images/580b57fcd9996e24bc43c341.png',
    },
    {
        name:'Cloud',
        fighter:'61',
        series: 'Final Fantasy',
        image:'https://www.smashbros.com/assets_v2/img/fighter/cloud/main2.png',       
        trailer:'https://www.youtube.com/embed/pWMoEtqciF0', 
        background:'https://images7.alphacoders.com/928/928770.jpStr',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Final_Fantasy_logo_with_japanese_name.svg/1200px-Final_Fantasy_logo_with_japanese_name.svg.png',
    },
    {
        name:'Corrin',
        fighter:'62',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/corrin/main2.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://nintendoeverything.com/wp-content/uploads/Fire-Emblem-Engage-screen.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cc/Fire_Emblem_series_logo.png/640px-Fire_Emblem_series_logo.png',
    },
    {
        name:'Bayonetta',
        fighter:'63',
        series: 'Bayonetta',
        image:'https://www.smashbros.com/assets_v2/img/fighter/bayonetta/main.png',       
        trailer:'https://www.youtube.com/embed/bUAtX8Ox7eI', 
        background:'https://images7.alphacoders.com/411/thumb-1920-411758.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/en/d/d5/Logo_for_Bayonetta.png',
    },
    {
        name:'Inkling',
        fighter:'64',
        series: 'Splatoon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/inkling/main.png',       
        trailer:'https://www.youtube.com/embed/GUYDXVDLmns', 
        background:'https://images.alphacoders.com/822/thumb-1920-822413.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Splatoon_Logo.png/800px-Splatoon_Logo.png',
    },
    {
        name:'Ridley',
        fighter:'65',
        series: 'Metroid',
        image:'https://www.smashbros.com/assets_v2/img/fighter/ridley/main.png',       
        trailer:'https://www.youtube.com/embed/V_XnbTayTH4', 
        background:'https://c4.wallpaperflare.com/wallpaper/423/239/662/metroid-wallpaper-preview.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/6/64/Metroid-Logo.png',
    },
    {
        name:'Simon',
        fighter:'66',
        series: 'Castlevania',
        image:'https://www.smashbros.com/assets_v2/img/fighter/simon/main.png',       
        trailer:'https://www.youtube.com/embed/L7iWXfZzEMc', 
        background:'https://wallpaperaccess.com/full/1308108.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Castlevania_logo.png/800px-Castlevania_logo.png',
    },
    {
        name:'Richter',
        fighter:'66E',
        series: 'Castlevania',
        image:'https://www.smashbros.com/assets_v2/img/fighter/richter/main.png',       
        trailer:'https://www.youtube.com/embed/L7iWXfZzEMc', 
        background:'https://wallpaperaccess.com/full/1308108.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Castlevania_logo.png/800px-Castlevania_logo.png',
    },
    {
        name:'King K. Rool',
        fighter:'67',
        series: 'Donkey Kong',
        image:'https://www.smashbros.com/assets_v2/img/fighter/king_k_rool/main.png',       
        trailer:'https://www.youtube.com/embed/5rxU5MEm0J4', 
        background:'https://images2.alphacoders.com/475/thumb-1920-475417.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/6/65/Donkey_Kong_logo.png',
    },
    {
        name:'Isabelle',
        fighter:'68',
        series: 'Animal Crossing',
        image:'https://www.smashbros.com/assets_v2/img/fighter/isabelle/main.png',       
        trailer:'https://www.youtube.com/embed/_3YNL0OWio0', 
        background:'https://www.xtrafondos.com/en/descargar.php?id=6456&resolucion=2560x1440',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/7/7c/Animal_Crossing_Leaf.svg/2149px-Animal_Crossing_Leaf.svg.png',
    },
    {
        name:'Incineroar',
        fighter:'69',
        series: 'Pokemon',
        image:'https://www.smashbros.com/assets_v2/img/fighter/incineroar/main.png',       
        trailer:'https://www.youtube.com/embed/tfQj1aQz8d8', 
        background:'https://wallpapercave.com/wp/wp7287550.jpg',
        logo:'https://external-preview.redd.it/tQged7mKJ3cUpNMq5IMeceZvyKP3cTyHqhNmKEQ0Vv8.png?width=640&crop=smart&auto=webp&s=5fc89334e792e2c9b294d1d328bf522cdede4cdf',
    },
    {
        name:'Pirahna Plant',
        fighter:'70',
        series: 'Super Mario Bros,',
        image:'https://www.smashbros.com/assets_v2/img/fighter/piranha_plant/main.png',       
        trailer:'https://www.youtube.com/embed/JGc6QZX68Zc', 
        background:'https://wallpaper-mania.com/wp-content/uploads/2018/09/High_resolution_wallpaper_background_ID_77700946652.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Mario_Series_Logo.svg/2560px-Mario_Series_Logo.svg.png',
    },
    {
        name:'Joker',
        fighter:'71',
        series: 'Persona 5',
        image:'https://www.smashbros.com/assets_v2/img/fighter/joker/main.png',       
        trailer:'https://www.youtube.com/embed/HU_Z8RKo_Ow', 
        background:'https://rare-gallery.com/uploads/posts/1001204-illustration-anime-cartoon-Persona-series-Persona-5-comics-mangaka-comic-book.png',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/c/cd/Persona_5_logo.svg/2560px-Persona_5_logo.svg.png',
    },
    {
        name:'Hero',
        fighter:'72',
        series: 'Dragon Quest',
        image:'https://www.smashbros.com/assets_v2/img/fighter/dq_hero/main8.png',       
        trailer:'https://www.youtube.com/embed/DncSvDnGGrc', 
        background:'https://wallpapercave.com/wp/wp336031.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/2/21/Dragon_Quest_-_Dai_no_daibouken_2020_logo.png',
    },
    {
        name:'Banjo and Kazooie',
        fighter:'73 ',
        series: 'Banjo and Kazooie',
        image:'https://www.smashbros.com/assets_v2/img/fighter/banjo_and_kazooie/main.png',       
        trailer:'https://www.youtube.com/embed/I67pPXS96UI  ', 
        background:'http://i.imgur.com/9pkQs0H.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/a/ab/Banjo_Kazooie_logo.png',
    },
    {
        name:'Terry',
        fighter:'74',
        series: 'Fatal Fury',
        image:'https://www.smashbros.com/assets_v2/img/fighter/terry/main.png',       
        trailer:'https://www.youtube.com/embed/INF7UURIF6s', 
        background:'https://wallpapercave.com/wp/wp2099888.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/en/b/b1/Fatalfurylogo.png',
    },
    {
        name:'Byleth',
        fighter:'75',
        series: 'Fire Emblem',
        image:'https://www.smashbros.com/assets_v2/img/fighter/byleth/main4.png',       
        trailer:'https://www.youtube.com/embed/3ExaJIB5Phk', 
        background:'https://www.pixelstalk.net/wp-content/uploads/images6/Fire-Emblem-Three-Houses-Wallpaper-Desktop.png',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Fire_Emblem_logo.svg/2560px-Fire_Emblem_logo.svg.png',
    },
    {
        name:'Min Min',
        fighter:'76',
        series: 'ARMS',
        image:'https://www.smashbros.com/assets_v2/img/fighter/minmin/main.png',       
        trailer:'https://www.youtube.com/embed/bgufXM4PHLg', 
        background:'https://images5.alphacoders.com/835/thumb-1920-835141.jpg',
        logo:'https://www.nicepng.com/png/detail/15-158129_nintendo-arms-guide-arms-nintendo-png.png',
    },
    {
        name:'Steve',
        fighter:'77',
        series: 'Minecraft',
        image:'https://www.smashbros.com/assets_v2/img/fighter/steve/main.png',       
        trailer:'https://www.youtube.com/embed/90Jve_qWnpc', 
        background:'https://wallpapers.com/images/featured/s2kxfahyg30sob8q.jpg',
        logo:'https://logos-world.net/wp-content/uploads/2020/05/Minecraft-Logo.png',
    },
    {
        name:'Sephiroth',
        fighter:'78',
        series: 'Final Fantasy',
        image:'https://www.smashbros.com/assets_v2/img/fighter/sephiroth/main.png',       
        trailer:'https://www.youtube.com/embed/pWMoEtqciF0', 
        background:'https://images7.alphacoders.com/928/928770.jpg',
        logo:'https://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Final_Fantasy_logo_with_japanese_name.svg/1200px-Final_Fantasy_logo_with_japanese_name.svg.png',
    },
    {
        name:'Pyra',
        fighter:'79',
        series: 'Xenoblade',
        image:'https://ssb.wiki.gallery/images/e/ec/Pyra_SSBU.png',       
        trailer:'https://www.youtube.com/embed/t-iNpDKuYb8', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2020/05/xenoblade_may_2020_wallpaper1.jpg?ssl=1',
        logo:'https://www.pngall.com/wp-content/uploads/4/Xenoblade-Chronicles-Logo.png',
    },
    {
        name:'Mythra',
        fighter:'80',
        series: 'Xenoblade',
        image:'https://ssb.wiki.gallery/images/5/58/Mythra_SSBU.png',       
        trailer:'https://www.youtube.com/embed/t-iNpDKuYb8', 
        background:'https://i0.wp.com/mynintendonews.com/wp-content/uploads/2020/05/xenoblade_may_2020_wallpaper1.jpg?ssl=1',
        logo:'https://www.pngall.com/wp-content/uploads/4/Xenoblade-Chronicles-Logo.png',
    },
    {
        name:'Kazuya',
        fighter:'81',
        series: 'Tekken',
        image:'https://www.smashbros.com/assets_v2/img/fighter/kazuya/main7.png',       
        trailer:'https://www.youtube.com/embed/2hPuRQz6IlM', 
        background:'https://images4.alphacoders.com/200/thumb-1920-200016.jpg',
        logo:'https://logos-world.net/wp-content/uploads/2021/03/Tekken-Logo.png',
    },
    {
        name:'Sora',
        fighter:'82',
        series: 'Kingdom Hearts',
        image:'https://www.smashbros.com/assets_v2/img/fighter/sora/main.png',       
        trailer:'https://www.youtube.com/embed/RvxuSoJIEvs', 
        background:'https://www.psu.com/wp/wp-content/uploads/2020/09/Kingdom-Hearts-III-PS4-Wallpapers-02.png',
        logo:'https://logos-world.net/wp-content/uploads/2021/02/Kingdom-Hearts-Emblem.png',
    },
]